# permissions to do viewer climanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: climanager-viewer-role
rules:
- apiGroups:
  - operator.openshift.io.operator.openshift.io
  resources:
  - climanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io.operator.openshift.io
  resources:
  - climanagers/status
  verbs:
  - get
