# permissions to do edit climanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: climanager-editor-role
rules:
- apiGroups:
  - operator.openshift.io.operator.openshift.io
  resources:
  - climanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io.operator.openshift.io
  resources:
  - climanagers/status
  verbs:
  - get
  - patch
  - update
